<a href="https://colab.research.google.com/github/palanipsb/Python-Learning/blob/main/Numpy_Workouts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Execercises

In [3]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

In [9]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
print(z.size)
print(z.itemsize)
print(z.size*z.itemsize)

10
8
80


In [19]:
np.info(z.__add__)

Return self+value.


In [21]:
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [30]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [31]:
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [40]:
z = np.arange(9)
print(z)

[0 1 2 3 4 5 6 7 8]


In [41]:
z = z.reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4]),)


In [50]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [76]:
z = np.random.random((2,3,3))
print(z)

[[[0.5174292  0.58503696 0.36676341]
  [0.35188763 0.22941547 0.26663516]
  [0.76531774 0.61646804 0.85018015]]

 [[0.11320244 0.56481188 0.75189791]
  [0.2502978  0.74250386 0.29120502]
  [0.96517555 0.98723877 0.41211458]]]


In [86]:
z = np.random.random((10,10))
print(z.min())
print(z.max())

0.001002016910526926
0.9954151586300406


In [89]:
z = np.random.random((30))
print(z.mean())

0.5756781728456694


In [173]:
z = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,10,11,12,13],[14,15,16,17,18],[19,20,21,22,23]])
print(z)
print('\n')
print(z[0:1],z[3:-1])

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]
 [19 20 21 22 23]]


[[1 2 3 4 5]] [[14 15 16 17 18]]


In [151]:
test = 'SIMPLILEARM'
print(test[1:7:2])

IPI
