<a href="https://colab.research.google.com/github/palanipsb/Python-Learning/blob/main/Numpy_Workouts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Execercises

In [2]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

In [ ]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(z.size)
print(z.itemsize)
print(z.size*z.itemsize)

10
8
80


In [ ]:
np.info(z.__add__)

Return self+value.


In [ ]:
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
z = np.arange(9)
print(z)

[0 1 2 3 4 5 6 7 8]


In [ ]:
z = z.reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4]),)


In [ ]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
z = np.random.random((2,3,3))
print(z)

[[[0.5174292  0.58503696 0.36676341]
  [0.35188763 0.22941547 0.26663516]
  [0.76531774 0.61646804 0.85018015]]

 [[0.11320244 0.56481188 0.75189791]
  [0.2502978  0.74250386 0.29120502]
  [0.96517555 0.98723877 0.41211458]]]


In [ ]:
z = np.random.random((10,10))
print(z.min())
print(z.max())

0.001002016910526926
0.9954151586300406


In [ ]:
z = np.random.random((30))
print(z.mean())

0.5756781728456694


In [30]:
z = np.arange(1,26).reshape(5,5)
print(z)
print('\n')
z[1:-1,1:-1] = 0
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[[ 1  2  3  4  5]
 [ 6  0  0  0 10]
 [11  0  0  0 15]
 [16  0  0  0 20]
 [21 22 23 24 25]]


In [31]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [38]:
z = np.array([[1,2],[3,4]])
print(z)
z = np.pad(z,pad_width=1,constant_values=5)
print(z)

[[1 2]
 [3 4]]
[[5 5 5 5]
 [5 1 2 5]
 [5 3 4 5]
 [5 5 5 5]]


In [106]:
z = np.arange(16).reshape(4,4)
print(z)
z[:, [0,-1]] = 0
z[[0,-1],:] = 0
print(z)
#print(z[[0,1,2],[1,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  0  0]
 [ 0  5  6  0]
 [ 0  9 10  0]
 [ 0  0  0  0]]


In [120]:
0 * np.nan
np.nan = np.nan
#np.info > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [124]:
z = np.arange(25).reshape(5,5)
z = z.transpose()
print(z)

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [133]:
z = np.arange(3)
z = np.diag(z,k=1)
print(z)

[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 2]
 [0 0 0 0]]


In [188]:
z = np.zeros(81,int).reshape(9,9)
z[::2,1::2] = 1
z[1::2,::2] = 1
print(z)

[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


In [187]:
z = np.arange(1,65).reshape(8,8)
print(z)
print(z[:,1::2])
print(z[1::2,:])
#print(z[:,1:-2:1])
#z[:,1::2] = -1
#z[1::2,:] = -1
print(z)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
[[ 2  4  6  8]
 [18 20 22 24]
 [34 36 38 40]
 [50 52 54 56]]
[[ 9 11 13 15]
 [25 27 29 31]
 [41 43 45 47]
 [57 59 61 63]]


In [203]:
z = np.arange(336).reshape(6,7,8)
print(z)
print(np.unravel_index(100,(z.shape)))
print(z[np.unravel_index(100,(z.shape))])

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [210]:
z = np.array([[0,1],[1,0]])
print(z)
z = np.tile(z,(2,3))
print(z)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [233]:
z = np.random.random((5,5))
print(z)
print(z.min())
print(z.max())
z1 = z-z.min()
print(z1)
z2 = z.max()-z.min()
print(z2)
z3 = z1/z2
print(z3)

[[0.61938288 0.83821963 0.48471049 0.69475953 0.75166951]
 [0.3321214  0.16335638 0.23602063 0.95261154 0.34297617]
 [0.82649285 0.88949895 0.13877411 0.84734013 0.04443536]
 [0.62637005 0.19404234 0.91661386 0.0360953  0.3634751 ]
 [0.41972009 0.36804392 0.64952416 0.7434252  0.94987651]]
0.036095298035444756
0.9526115423783127
[[0.58328758 0.80212433 0.44861519 0.65866423 0.71557422]
 [0.2960261  0.12726109 0.19992534 0.91651624 0.30688087]
 [0.79039755 0.85340365 0.10267882 0.81124483 0.00834006]
 [0.59027475 0.15794704 0.88051856 0.         0.3273798 ]
 [0.38362479 0.33194862 0.61342886 0.7073299  0.91378121]]
0.9165162443428679
[[0.63641816 0.87518834 0.48947871 0.71866073 0.78075454]
 [0.32299057 0.13885306 0.21813616 1.         0.33483408]
 [0.86239339 0.9311386  0.11203164 0.88513961 0.00909974]
 [0.64404178 0.17233415 0.96072335 0.         0.35720022]
 [0.41856846 0.3621852  0.66930495 0.77175926 0.99701583]]


In [236]:
z = np.arange(1,10).reshape(3,3)
print(z)
min = z.min()
max = z.max()
ave = max - min
print(min,max,ave)
z1 = z-min
print(z1)
z2 = z1/ave
print(z2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 9 8
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]
