<a href="https://colab.research.google.com/github/palanipsb/Python-Learning/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os

In [13]:
x = tf.constant([[2,3]])
y = tf.constant([[4],[5]])

In [14]:
z = x+y
print(z)

tf.Tensor(
[[6 7]
 [7 8]], shape=(2, 2), dtype=int32)


In [16]:
print(5*z)

tf.Tensor(
[[30 35]
 [35 40]], shape=(2, 2), dtype=int32)


In [18]:
print(z@tf.transpose(z))

tf.Tensor(
[[ 85  98]
 [ 98 113]], shape=(2, 2), dtype=int32)


In [22]:
tf.concat([z,z,z],axis=1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[6, 7, 6, 7, 6, 7],
       [7, 8, 7, 8, 7, 8]], dtype=int32)>

In [28]:
print(tf.reduce_sum(z))

tf.Tensor(28, shape=(), dtype=int32)


In [32]:
print(tf.convert_to_tensor(np.array([1,2,3])))

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [33]:
if tf.config.list_physical_devices('GPU'):
    print("GPU is available")
else:
    print("GPU is not available")

GPU is available


In [ ]:
x =